### ISSUE TITLE
Add all "OB Annexed Lists" to site

### ISSUE THREAD

**Issue by ronaldtse** [ituob/ituob.org#8] opened 2019-07-11 01:55 UTC
<img width="912" alt="Screen Shot 2019-07-11 at 9 54 16 AM" src="https://user-images.githubusercontent.com/11865/61016336-da6b6e00-a3c1-11e9-966d-771b03d482eb.png">

There are a number of other OB annexed lists:
https://www.itu.int/en/publications/ITU-T/Pages/publications.aspx?parent=T-SP&view=T-SP1

**Comment by strogonoff** [comment] 2019-07-16 08:13
Duplicate of https://github.com/ituob/itu-ob-data/issues/21

**Closed by strogonoff** 2019-07-16 08:13 UTC
Labels: enhancement
